version: '3'
services:
  pilot:
    build:
      context: ./vendor/savvywombat/pilot/docker/php-8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
        NODE_VERSION: '${NODE_VERSION:-18}'
    image: savvywombat/pilot/php-8.2
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${HTTP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:5173'
    environment:
      WWWUSER: '${WWWUSER}'
    volumes:
      - '.:/var/www/html'
    networks:
      - pilot
networks:
  pilot:
    driver: bridge